name: Build Windows

on: 
  push:

  # Manual run
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    #defaults:
    #  run:
    #    working-directory: python3-windows    
    strategy:
      matrix:
        env:
          #- { ARCH: win32, PYVER: 3.6.9 }
          #- { ARCH: x64, PYVER: 3.6.9 }

          #- { ARCH: win32, PYVER: 3.7.9 }
          #- { ARCH: x64, PYVER: 3.7.9 }

          #- { ARCH: win32, PYVER: 3.8.9 }
          #- { ARCH: x64, PYVER: 3.9.9 }

          #- { ARCH: Win32, PYVER: 3.9.9 }
          - { ARCH: x64, PYVER: 3.9.9 }

          #- { ARCH: win32, PYVER: 3.10.4 }
          #- { ARCH: x64, PYVER: 3.10.4 }
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    #- name: Checkout python repo
    #  uses: actions/checkout@v3
    #  with:
    #    repository: python/cpython
    #    ref: v${{ matrix.env.PYVER }}
    #- name: Building      
    #  run: |      
    #    PCBuild\build.bat -p ${{ matrix.env.ARCH }} -e -c Release   
    - name: Create package
      run: |
        cd C:\msys64\mingw32\bin
        ls
      #  7z a python3-android-${{ matrix.env.PYVER }}-${{ matrix.env.ARCH }}.zip PCBuild\*
      #run: |       
      #  if (Test-Path -Path "PCBuild\amd64") {
      #    Rename-Item PCBuild\amd64 ${{ matrix.env.ARCH }}
      #  } elseif (Test-Path -Path "PCBuild\win32") {
      #    Rename-Item PCBuild\win32 ${{ matrix.env.ARCH }}   
      #  }         
      #  cd PCBuild\${{ matrix.env.ARCH }}
      #  7z a -t7z python3-android-${{ matrix.env.PYVER }}-${{ matrix.env.ARCH }}.zip * -r      
    - name: Save build
      uses: actions/upload-artifact@v2
      with:
        #path: PCBuild\${{ matrix.env.ARCH }}\python3-android-${{ matrix.env.PYVER }}-${{ matrix.env.ARCH }}.zip
        path: python3-android-${{ matrix.env.PYVER }}-${{ matrix.env.ARCH }}.zip
        if-no-files-found: error