name: Build Windows

on: 
  push:

  # Manual run
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    #defaults:
    #  run:
    #    working-directory: python3-windows    
    strategy:
      matrix:
        env:
          #- { ARCH: win32, PYVER: 3.6.9 }
          #- { ARCH: x64, PYVER: 3.6.9 }

          #- { ARCH: win32, PYVER: 3.7.9 }
          #- { ARCH: x64, PYVER: 3.7.9 }

          #- { ARCH: win32, PYVER: 3.8.9 }
          #- { ARCH: x64, PYVER: 3.9.9 }

          #- { ARCH: win32, PYVER: 3.9.9 }
          - { ARCH: x64, PYVER: 3.9.9 }

          #- { ARCH: win32, PYVER: 3.10.4 }
          #- { ARCH: x64, PYVER: 3.10.4 }
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout python repo
      uses: actions/checkout@v3
      with:
        repository: python/cpython
        ref: v${{ matrix.env.PYVER }}
    - name: Building
      shell: pwsh
      run: |      
        ls
        ls -l PCBuild
        PCBuild\build.bat -p ${{ matrix.env.ARCH }}
        ls
        ls -l PCBuild