name: Build Windows

on: 
  push:
  # Manual run
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, '-android')
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./python3-linux    
    strategy:
      matrix:
        env:
          - { ARCH: x86, PYVER: 3.6.9 }
          - { ARCH: x64, PYVER: 3.6.9 }

          - { ARCH: x86, PYVER: 3.7.9 }
          - { ARCH: x64, PYVER: 3.7.9 }

          - { ARCH: x86, PYVER: 3.8.9 }
          - { ARCH: x64, PYVER: 3.9.9 }

          - { ARCH: x86, PYVER: 3.9.9 }
          - { ARCH: x64, PYVER: 3.9.9 }

          - { ARCH: x86, PYVER: 3.10.4 }
          - { ARCH: x64, PYVER: 3.10.4 }
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: python/cpython
    - name: Building
      run: |      
        dir